openapi: 3.0.1
info:
  title: Sample Application Flow OAuth2 Project
  description: This is an example of using OAuth2 Application Flow in a specification
    to describe security to your API.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/dinhtai0401/BasicOAuth/1.0.0
  description: SwaggerHub API Auto Mocking
security:
- securitySchemes:
  - write
  - read
paths:
  /users:
    get:
      summary: Server heartbeat operation
      description: This operation shows how to override the global security defined
        above, as we want to open it up for all users.
      operationId: usersGET
      responses:
        "200":
          description: OK
      security: []
      x-swagger-router-controller: Default
components:
  schemas: {}
  securitySchemes:
    application:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:4000/auth/google
          scopes:
            write: username in username
            read: username in username
